#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCustomerTechnologyMetadata.h"
@protocol SWGCustomerTechnologyMetadata;
@class SWGCustomerTechnologyMetadata;



@protocol SWGCustomerTechnology
@end

@interface SWGCustomerTechnology : SWGObject

/* Primary key [optional]
 */
@property(nonatomic) NSString* _id;
/* The primary key of the related *CustomerTechnology* [optional]
 */
@property(nonatomic) NSString* parentId;
/* The primary key of the related *Customer* [optional]
 */
@property(nonatomic) NSString* customerId;
/* The primary key of the related *CustomerLocation* [optional]
 */
@property(nonatomic) NSString* customerLocationId;
/* The primary key of the related *Org* [optional]
 */
@property(nonatomic) NSString* orgId;
/* chat nickname [optional]
 */
@property(nonatomic) NSString* nickname;
/* technology type [optional]
 */
@property(nonatomic) NSString* type;
/* Is device in critical status [optional]
 */
@property(nonatomic) NSNumber* critical;
/* is active [optional]
 */
@property(nonatomic) NSNumber* active;
/* friendly label [optional]
 */
@property(nonatomic) NSString* label;
/* device make [optional]
 */
@property(nonatomic) NSString* make;
/* device model [optional]
 */
@property(nonatomic) NSString* model;
/* device serial [optional]
 */
@property(nonatomic) NSString* serialNumber;
/* firmware version [optional]
 */
@property(nonatomic) NSString* version;
/* ip address [optional]
 */
@property(nonatomic) NSString* ipAddress;
/* mac address [optional]
 */
@property(nonatomic) NSString* macAdddress;
/* Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee's data [optional]
 */
@property(nonatomic) NSString* externalId;
/* technology notes [optional]
 */
@property(nonatomic) NSString* notes;
/* device location relative to location [optional]
 */
@property(nonatomic) NSString* location;
/* extended status details [optional]
 */
@property(nonatomic) NSString* statusDetail;
/* Created [optional]
 */
@property(nonatomic) NSDate* created;
/* Updated [optional]
 */
@property(nonatomic) NSDate* updated;
/* Last time contact with device was attempted [optional]
 */
@property(nonatomic) NSDate* lastChecked;
/* Last time contact with the device was made [optional]
 */
@property(nonatomic) NSDate* lastSeen;
/* Last time a change was recorded [optional]
 */
@property(nonatomic) NSDate* lastChanged;
/* Refernce number [optional]
 */
@property(nonatomic) NSString* pciSscRefNo;
/* dependencies [optional]
 */
@property(nonatomic) NSString* ptsDeviceDependencies;
/* list [optional]
 */
@property(nonatomic) NSNumber* appPaDssListed;
/* expiration [optional]
 */
@property(nonatomic) NSDate* paDdsExpireDate;

@property(nonatomic) SWGCustomerTechnologyMetadata* metadataValues;
/* PCI compliance status [optional]
 */
@property(nonatomic) NSString* pciCompliant;
/* Monitoring policy [optional]
 */
@property(nonatomic) NSString* policy;
/* Status [optional]
 */
@property(nonatomic) NSString* status;

@end
