#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCustomerUser
@end

@interface SWGCustomerUser : SWGObject

/* Primary key [optional]
 */
@property(nonatomic) NSString* _id;
/* Related *Customer* primary key [optional]
 */
@property(nonatomic) NSString* customerId;
/* Related *CustomerLocation* primary key [optional]
 */
@property(nonatomic) NSString* customerLocationId;
/* First name 
 */
@property(nonatomic) NSString* firstName;
/* Last name 
 */
@property(nonatomic) NSString* lastName;
/* Full name [optional]
 */
@property(nonatomic) NSString* fullName;
/* Email 
 */
@property(nonatomic) NSString* email;
/* Mobile/SMS phone [optional]
 */
@property(nonatomic) NSString* smsNumber;
/* Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee's data [optional]
 */
@property(nonatomic) NSString* externalId;
/* Language (ISO-2) [optional]
 */
@property(nonatomic) NSString* lang;

@end
