#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCustomerTechnologySummary
@end

@interface SWGCustomerTechnologySummary : SWGObject

/* Primary key [optional]
 */
@property(nonatomic) NSString* _id;
/* The primary key of the related *CustomerTechnology* [optional]
 */
@property(nonatomic) NSString* parentId;
/* Type [optional]
 */
@property(nonatomic) NSString* type;
/* Is device in critial status [optional]
 */
@property(nonatomic) NSNumber* critical;
/* is active [optional]
 */
@property(nonatomic) NSNumber* active;
/* device make [optional]
 */
@property(nonatomic) NSString* make;
/* device model [optional]
 */
@property(nonatomic) NSString* model;
/* Last time contact with device was attempted [optional]
 */
@property(nonatomic) NSDate* lastChecked;
/* Last time contact with the device was made [optional]
 */
@property(nonatomic) NSDate* lastSeen;
/* Last time a change was recorded [optional]
 */
@property(nonatomic) NSDate* lastChanged;
/* PCI compliance status [optional]
 */
@property(nonatomic) NSString* pciCompliant;
/* Monitoring policy [optional]
 */
@property(nonatomic) NSString* policy;
/* Status [optional]
 */
@property(nonatomic) NSString* status;

@end
