#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIssueMetadata.h"
@protocol SWGIssueMetadata;
@class SWGIssueMetadata;



@protocol SWGIssue
@end

@interface SWGIssue : SWGObject

/* Primary key [optional]
 */
@property(nonatomic) NSString* _id;
/* Reference number [optional]
 */
@property(nonatomic) NSString* referenceNum;
/* Org Cases/Tickets [optional]
 */
@property(nonatomic) NSString* remoteId;
/* Related *Customer* primary key 
 */
@property(nonatomic) NSString* customerId;
/* Related *Customer* name [optional]
 */
@property(nonatomic) NSString* customerName;
/* Related *Customer* email [optional]
 */
@property(nonatomic) NSString* customerEmail;
/* Related *CustomerLocation* primary key 
 */
@property(nonatomic) NSString* customerLocationId;
/* Related *CustomerLocation* name [optional]
 */
@property(nonatomic) NSString* customerLocationName;
/* Related *CustomerUser* primary key 
 */
@property(nonatomic) NSString* customerUserId;
/* Related *CustomerUser* name [optional]
 */
@property(nonatomic) NSString* customerUserName;
/* Related *CustomerUser* email [optional]
 */
@property(nonatomic) NSString* customerUserEmail;
/* Related *Admin User* primary key [optional]
 */
@property(nonatomic) NSString* userId;
/* Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee's data [optional]
 */
@property(nonatomic) NSString* externalId;
/* Type [optional]
 */
@property(nonatomic) NSString* type;
/* Category [optional]
 */
@property(nonatomic) NSString* category;
/* Details [optional]
 */
@property(nonatomic) NSString* details;
/* Status [optional]
 */
@property(nonatomic) NSString* status;
/* Job type [optional]
 */
@property(nonatomic) NSString* job;
/* Resolution [optional]
 */
@property(nonatomic) NSString* resolution;
/* Created [optional]
 */
@property(nonatomic) NSDate* created;
/* Updated [optional]
 */
@property(nonatomic) NSDate* updated;
/* Technician job scheduled [optional]
 */
@property(nonatomic) NSDate* scheduledTime;
/* Technician en-route for job [optional]
 */
@property(nonatomic) NSDate* enrouteTime;
/* Technician arrived at job [optional]
 */
@property(nonatomic) NSDate* arrivalTime;
/* Technician departed job [optional]
 */
@property(nonatomic) NSDate* departureTime;
/* IDR ISQ [optional]
 */
@property(nonatomic) NSString* idrIsq;
/* IDR Process [optional]
 */
@property(nonatomic) NSString* idrProcess;
/* IDR Resolution [optional]
 */
@property(nonatomic) NSString* idrResolution;
/* Tech Support Minutes [optional]
 */
@property(nonatomic) NSNumber* techSupportMinutes;
/* Issue special notes (empty if no access) [optional]
 */
@property(nonatomic) NSString* specialNotes;
/* Unmanaged by Boomtown SLA [optional]
 */
@property(nonatomic) NSNumber* unmanaged;

@property(nonatomic) SWGIssueMetadata* metadataValues;

@end
