#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGIssueChatHistoryTranscript.h"
@protocol SWGIssueChatHistoryTranscript;
@class SWGIssueChatHistoryTranscript;



@protocol SWGIssueChatHistory
@end

@interface SWGIssueChatHistory : SWGObject

/* Primary key [optional]
 */
@property(nonatomic) NSString* _id;
/* Object Id [optional]
 */
@property(nonatomic) NSString* objectId;
/* Object Scope [optional]
 */
@property(nonatomic) NSString* objectScope;
/* Chat Type [optional]
 */
@property(nonatomic) NSNumber* chatType;
/* Chat Status [optional]
 */
@property(nonatomic) NSNumber* chatStatus;
/* Billing Status [optional]
 */
@property(nonatomic) NSNumber* billingStatus;
/* Title [optional]
 */
@property(nonatomic) NSString* title;
/* Sub Title [optional]
 */
@property(nonatomic) NSString* subtitle;
/* Duration Plus [optional]
 */
@property(nonatomic) NSNumber* durationPlus;
/* Duration [optional]
 */
@property(nonatomic) NSNumber* duration;

@property(nonatomic) SWGIssueChatHistoryTranscript* transcript;
/* Eternal rpid [optional]
 */
@property(nonatomic) NSString* externalRpid;
/* Eternal lpid [optional]
 */
@property(nonatomic) NSString* externalLpid;
/* Eternal Id [optional]
 */
@property(nonatomic) NSString* externalId;
/* Created [optional]
 */
@property(nonatomic) NSDate* created;
/* Updated [optional]
 */
@property(nonatomic) NSDate* updated;

@end
