#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGOrgTeam
@end

@interface SWGOrgTeam : SWGObject

/* Primary key [optional]
 */
@property(nonatomic) NSString* _id;
/* Name [optional]
 */
@property(nonatomic) NSString* name;
/* Hashtag nickname for group mentions in chat [optional]
 */
@property(nonatomic) NSString* nickname;
/* Description [optional]
 */
@property(nonatomic) NSString* _description;
/* Email [optional]
 */
@property(nonatomic) NSString* email;
/* Phone [optional]
 */
@property(nonatomic) NSString* phone;
/* Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee's data [optional]
 */
@property(nonatomic) NSString* externalId;
/* Avatar (URL) [optional]
 */
@property(nonatomic) NSString* avatar;
/* Automatically set this OrgTeam as first contact on new *Issues* from related *Customers* [optional]
 */
@property(nonatomic) NSNumber* autoAssignRoute;
/* Automatically set this OrgTeam as sponsor for related *Customer* billing [optional]
 */
@property(nonatomic) NSNumber* autoAssignSponsor;
/* Status [optional]
 */
@property(nonatomic) NSString* status;
/* Type/Category [optional]
 */
@property(nonatomic) NSString* type;
/* This OrgTeam is exclusive within its type/category [optional]
 */
@property(nonatomic) NSNumber* exclusive;
/* This OrgTeam is published in the Connect app [optional]
 */
@property(nonatomic) NSNumber* published;
/* Name of this OrgTeam as it appears in the Connect app [optional]
 */
@property(nonatomic) NSString* publishedName;
/* This OrgTeam has private label branding in the Connect app [optional]
 */
@property(nonatomic) NSNumber* privateLabel;
/* Private label link color (if private_label is true) [optional]
 */
@property(nonatomic) NSString* linkColor;
/* Private label text color (if private_label is true) [optional]
 */
@property(nonatomic) NSString* textColor;
/* Private label brand color 1 (if private_label is true) [optional]
 */
@property(nonatomic) NSString* brandColor1;
/* Private label brand color 2 (if private_label is true) [optional]
 */
@property(nonatomic) NSString* brandColor2;
/* Private label logo (if private_label is true) [optional]
 */
@property(nonatomic) NSString* brandLogo1x;
/* Private label logo [x2] (if private_label is true) [optional]
 */
@property(nonatomic) NSString* brandLogo2x;
/* Private label logo [x3] (if private_label is true) [optional]
 */
@property(nonatomic) NSString* brandLogo3x;
/* Support Email [optional]
 */
@property(nonatomic) NSString* supportEmail;
/* Support Phone [optional]
 */
@property(nonatomic) NSString* supportPhone;
/* Support Website (URL) [optional]
 */
@property(nonatomic) NSString* supportUrl;
/* Created [optional]
 */
@property(nonatomic) NSDate* created;
/* Updated [optional]
 */
@property(nonatomic) NSDate* updated;

@end
