#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGOrg
@end

@interface SWGOrg : SWGObject

/* Primary key [optional]
 */
@property(nonatomic) NSString* _id;
/* Business name [optional]
 */
@property(nonatomic) NSString* name;
/* Business legal name [optional]
 */
@property(nonatomic) NSString* nameLegal;
/* Hashtag nickname for group mentions in chat [optional]
 */
@property(nonatomic) NSString* nickname;
/* The chatunication channel id [optional]
 */
@property(nonatomic) NSString* chatId;
/* Description [optional]
 */
@property(nonatomic) NSString* _description;
/* Address 1 [optional]
 */
@property(nonatomic) NSString* street1;
/* Address 2 [optional]
 */
@property(nonatomic) NSString* street2;
/* City [optional]
 */
@property(nonatomic) NSString* city;
/* State/Province (2 char code) [optional]
 */
@property(nonatomic) NSString* state;
/* ZIP/Postal Code [optional]
 */
@property(nonatomic) NSString* zipcode;
/* Latitude [optional]
 */
@property(nonatomic) NSNumber* latitude;
/* Longitude [optional]
 */
@property(nonatomic) NSNumber* longitude;
/* Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee's data [optional]
 */
@property(nonatomic) NSString* externalId;
/* Default OrgTeam's id [optional]
 */
@property(nonatomic) NSString* defaultOrgTeamId;
/* Email [optional]
 */
@property(nonatomic) NSString* email;
/* Phone [optional]
 */
@property(nonatomic) NSString* phone;
/* Web site (URL) [optional]
 */
@property(nonatomic) NSString* website;
/* Avatar (URL) [optional]
 */
@property(nonatomic) NSString* avatar;
/* Created [optional]
 */
@property(nonatomic) NSDate* created;
/* Updated [optional]
 */
@property(nonatomic) NSDate* updated;

@end
