#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGOrgReportItem
@end

@interface SWGOrgReportItem : SWGObject


@property(nonatomic) NSString* issueID;

@property(nonatomic) NSString* referenceNum;

@property(nonatomic) NSString* orgCasesTickets;

@property(nonatomic) NSString* issueStatus;

@property(nonatomic) NSString* jobStatus;

@property(nonatomic) NSString* adminUserOrgTeamUser;

@property(nonatomic) NSString* org;

@property(nonatomic) NSString* issueType;

@property(nonatomic) NSString* workOrderType;

@property(nonatomic) NSString* issueCategory;

@property(nonatomic) NSString* customerName;

@property(nonatomic) NSString* customerLocationSiteName;

@property(nonatomic) NSString* customerLocationStreet1;

@property(nonatomic) NSString* customerLocationStreet2;

@property(nonatomic) NSString* city;

@property(nonatomic) NSString* state;

@property(nonatomic) NSString* zipcode;

@property(nonatomic) NSString* country;

@property(nonatomic) NSString* timeZoneOfScheduledActionDateAndTime;

@property(nonatomic) NSDate* issueCreationDateAndTime;

@property(nonatomic) NSDate* dateAndTimeScheduledByProjectManager;

@property(nonatomic) NSDate* scheduledDateAndTime;

@property(nonatomic) NSDate* startDateAndTime;

@property(nonatomic) NSDate* resolvedDateAndTime;

@property(nonatomic) NSString* remoteWaitTime;

@property(nonatomic) NSNumber* serviceTime;

@property(nonatomic) NSString* resolution;

@property(nonatomic) NSNumber* nPS;

@property(nonatomic) NSNumber* technicianRating;

@property(nonatomic) NSNumber* total;

@property(nonatomic) NSString* paymentStatus;

@property(nonatomic) NSString* specialNotes;

@property(nonatomic) NSString* techSupportMinutes;

@end
