#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGShipment
@end

@interface SWGShipment : SWGObject

/* Primary key [optional]
 */
@property(nonatomic) NSString* _id;
/* Description [optional]
 */
@property(nonatomic) NSString* _description;
/* Pieces [optional]
 */
@property(nonatomic) NSString* pieces;
/* Carrier 
 */
@property(nonatomic) NSString* carrier;
/* Carrier Tracking Number 
 */
@property(nonatomic) NSString* carrierTracking;
/* ETA [optional]
 */
@property(nonatomic) NSDate* estimatedArrival;
/* Status [optional]
 */
@property(nonatomic) NSString* status;
/* Created [optional]
 */
@property(nonatomic) NSDate* created;
/* Updated [optional]
 */
@property(nonatomic) NSDate* updated;

@end
