#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Boomtown Cloud API
* The REST API for 3rd-party integrations with the Boomtown Cloud. Authentication is provided as HTTP headers using the credentials provided to you at sign-up time. To access the Cloud API, is recommended to use the open source [Boomtown Cloud SDK](https://github.com/goboomtown) as this handles authentication and data-handling for you, but plain REST can be used as well. If not using a provided SDK, provide authentication details via HTTP headers `X-Boomtown-Token` and `X-Boomtown-Signature` as described [in the SDK documentation](https://github.com/goboomtown/cloud-sdk-php#documentation-for-authorization) 
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGUploadFile
@end

@interface SWGUploadFile : SWGObject

/* Primary key [optional]
 */
@property(nonatomic) NSString* _id;
/* Owner entity [optional]
 */
@property(nonatomic) NSString* object;
/* Owner entity id [optional]
 */
@property(nonatomic) NSString* objectId;
/* MIME type [optional]
 */
@property(nonatomic) NSString* type;
/* Download URL [optional]
 */
@property(nonatomic) NSString* file;
/* Filesize in bytes [optional]
 */
@property(nonatomic) NSNumber* size;
/* Original filename [optional]
 */
@property(nonatomic) NSString* name;
/* Category [optional]
 */
@property(nonatomic) NSString* tag;
/* Additional notes [optional]
 */
@property(nonatomic) NSString* notes;
/* Preview URL, replace trailing dimensions as needed [optional]
 */
@property(nonatomic) NSString* thumbnail;
/* Created [optional]
 */
@property(nonatomic) NSDate* created;

@end
